### PR TITLE
Make wget indempotent

### PR DESCRIPTION
**Pull request by gjedeer**
This wget call used to download to csf.tgz.1 when called more than once - fixed

### CODE REVIEW

**Comment by jloh** [comment]
Thanks for this!

**Comment by jloh** [comment]
Actually, any chance you want to change the `wget` command to a `get_url` command in Ansible?

**Comment by jloh** [comment]
Thanks for this, ended up doing it as a separate PR though!

**Comment by gjedeer** [comment]
Cool, nice that you're still working on this role. I was going to do that but distractions happened.

**Pull request closed without merging**
